### ISSUE TITLE
Compile error on Debian 9

### ISSUE THREAD

**Issue by Mrifk** [sjmulder/trickle#1]
When I run `make` on my Debian 9 machine, I get the following output:

```
cc -ansi -Wall  -o trickle trickle.c
In file included from trickle.c:12:0:
trickle.h:2:18: error: field ‘delay’ has incomplete type
  struct timespec delay;
                  ^~~~~
trickle.c: In function ‘main’:
trickle.c:31:3: warning: implicit declaration of function ‘nanosleep’ [-Wimplicit-function-declaration]
   nanosleep(&opts.delay, NULL);
   ^~~~~~~~~
Makefile:11: recipe for target 'trickle' failed
make: *** [trickle] Error 1
```
No binary is produced.

**Comment by sjmulder** [comment]
I can't test until a little later but I think this should be fixed by adding the following to the very top of trickle.c:

    #define _BSD_SOURCE
    #define _DEFAULT_SOURCE

Thanks for reporting!

**Comment by sjmulder** [comment]
I've applied the above on master. I'm fairly certain it should fix the error but please let me know if it doesn't.

**Comment by Mrifk** [comment]
It works now! :D

**Comment by sjmulder** [comment]
Good to hear!
