### ISSUE TITLE
Create brew formula

### ISSUE THREAD

**Issue by AnimiVulpis** [sjmulder/trickle#2]
Would you take the time to create a [homebrew formula](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md)?

I would help out if you don't want to do it (if you are ok with that), but because I have 0 experience with ruby it might take some time.

**Comment by sjmulder** [comment]
Sure, I'm not sure when I can get to it, though.

Some notes for the formula:
 - `-lutil` is not required on macOS, hence build with: `make LDLIBS_tritty=""`
 - There is no install target. Just copy the two binaries.

In the meantime however, you can just download and type `make`. There are no extra dependencies.

**Comment by nickolasburr** [comment]
I'd be more than happy to create the formula, just let me know.

**Comment by sjmulder** [comment]
By all means, I appreciate that very much.

**Comment by nickolasburr** [comment]
Not a problem! I will need a tagged release of trickle for the formula though, in case someone doesn't want the bottled version.

**Comment by sjmulder** [comment]
Fair enough, but before tagging 1.0 I want to add a licence, extend the readme a little, and add man pages. This shouldn't take too long, and it would seem of little use to tag a pre-release version for only a day or two. If you feel differently however I'll happily oblige.

**Comment by nickolasburr** [comment]
No, I totally understand and agree. In that case, I can either change the download strategy to manually clone the repository and install it that way, or I can wait for the initial release. Totally up to you. The only caveat worth mentioning is that Homebrew can be a little temperamental with versioning, so if I tag version `1.0` in the formula and then you release a version `1.0`, that will require manually adding a revision to the formula. Not a huge deal, but worth noting.

**Comment by sjmulder** [comment]
If you're still up for it, I've just tagged 1.0! There is now an install target, too:

```
make LDLIBS_tritty=""
make install
```

The install target uses a _PREFIX_ variable which is set to _/usr/local_ by default, which I think should be correct for Homebrew. If not, it can be set though a make argument. There is also an uninstall target.

**Comment by nickolasburr** [comment]
All set on this. You can find the formula at https://github.com/nickolasburr/homebrew-pfa, and the bottles are located at https://dl.bintray.com/nickolasburr/homebrew-bottles. Let me know if you need anything else.

For new releases, feel free to send a PR or notify me about an update.

**Comment by sjmulder** [comment]
I didn't realise it was you, the same person who did the sc-im formula! FYI, that project really doesn't require brew ncurses – the one issue that prevented it from working with system ncurses (which includes wide character support) was long fixed.

This formula looks great. I'll update the readme to point to it.

Just as an aside, I understand that Homebrew wants you to be specific about supported releases for bottles but I'm surprised that need to have to have different copies (or links) of the file to match the naming scheme even though they are the same.

**Comment by sjmulder** [comment]
Readme updated. Thanks again!
